# ./docker-compose.yml
version: "3.9"

services:
  # --------------------------
  # TimescaleDB / PostgreSQL
  # --------------------------
  db:
    image: timescale/timescaledb:latest-pg16 # Use latest TimescaleDB image (PostgreSQL 16)
    container_name: kronicle-db
    env_file:
      - .secrets
      - .env
    environment:
      # Set from env file or .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - kronicle-db-data:/var/lib/postgresql/data # Persist DB data
    ports:
      - "5432:5432" # optional, local access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      retries: 15
      timeout: 2s
    networks:
      - kronicle-net # Shared network for app <> db communication
    restart: unless-stopped # Automatically restart unless stopped manually

  # --------------------------
  # Kronicle DB/init container
  # --------------------------
  app:
    image: ghcr.io/logistica-dev/kronicle:latest
    container_name: kronicle-app
    env_file:
      - .secrets
      - .env
    build:
      context: .
      dockerfile: docker/init/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      KRONICLE_DB_HOST: db
      KRONICLE_DB_PORT: 5432
      KRONICLE_DB_NAME: ${POSTGRES_DB}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      KRONICLE_CHAN_CREDS: ${KRONICLE_CHAN_CREDS}
      KRONICLE_RBAC_CREDS: ${KRONICLE_RBAC_CREDS}

      KRONICLE_SU_INFO: ${KRONICLE_SU_INFO}
    networks:
      - kronicle-net # Same network as db
    restart: unless-stopped # Keep container running unless manually stopped

# ------------------------------
# Persisted volumes
# ------------------------------
volumes:
  kronicle-db-data: # Persistent data for TimescaleDB

# ------------------------------
# Shared network
# ------------------------------
networks:
  kronicle-net: # Custom network for container communication
